# Generated by Django 3.0.6 on 2020-05-26 06:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField(max_length=10)),
                ('birthday', models.DateField(max_length=20)),
                ('age', models.IntegerField()),
                ('img', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='New_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField(max_length=10)),
                ('birthday', models.DateField(max_length=20)),
                ('age', models.IntegerField()),
                ('img', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('time', models.DateField(default='2020-05-26', max_length=20)),
                ('read_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('img', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=False, max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Author')),
                ('new_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.New_types')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateField(default='2020-05-26', max_length=20)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Users')),
            ],
        ),
    ]
