# Generated by Django 3.0.6 on 2020-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pwd',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default='2020-05-27', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateField(default='2020-05-27', max_length=20),
        ),
    ]
