# Generated by Django 3.0.6 on 2020-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200527_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default='2020-05-28', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateField(default='2020-05-28', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.CharField(max_length=50),
        ),
    ]
